import "@/styles/globals.css";

// import { createClient } from '@/utils/supabase/server'
// import { cookies } from 'next/headers'

export const metadata = {
  title: "Bestro",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
